name: Deploy GitHub Pages

on:
  push:
    branches:
      - master
      - feat/doc-to-github-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3

      - name: Install less
        run: sudo npm install -g less

      - name: Install yui-compressor
        run: sudo apt-get install -y yui-compressor

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, dom, fileinfo, mysql, redis, opcache
          tools: composer

      - name: Generate
        run: make generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output_prod
